<a href="https://colab.research.google.com/github/Alen-8080/Learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [14]:
#please provide your answer below this line.
import numpy as np
a = np.arange(0, 9).reshape(3, 3)
b = np.arange(1, 10).reshape(3, 3)
print(" Matrix A")
print(a)
print(" Matrix B")
print(b)
dot = np.dot(a, b)
print("Dot product of Matrix")
print(dot)
print("Transpose of Dot product")
print(dot.T)

 Matrix A
[[0 1 2]
 [3 4 5]
 [6 7 8]]
 Matrix B
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dot product of Matrix
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
Transpose of Dot product
[[ 18  54  90]
 [ 21  66 111]
 [ 24  78 132]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [25]:
#please provide your answer below this line.
import numpy as np
A = [[55,25,15],[30,44,2],[11,45,77]]
a= np.array(A)
print("Matrix A ")
print(a)
print("Determinant of A")
print(np.linalg.det(a))

Matrix A 
[[55 25 15]
 [30 44  2]
 [11 45 77]]
Determinant of A
137180.0000000001
