<a href="https://colab.research.google.com/github/Alen-8080/Learn.py/blob/main/TASK_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [2]:
#please enter your code below this line.
import numpy as np
a= np.arange(0,9).reshape(3,3)
print(np.sum(a))

36


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [5]:
#please enter your code below this line.
import numpy as np
a = np.arange(0,9).reshape(3,3)
print(" MAtrix ")
print(a)
print(" Row wise Sum")
print(np.sum(a,axis=0))
print(" column Wise Sum")
print(np.sum(a,axis=1))

 MAtrix 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
 Row wise Sum
[ 9 12 15]
 column Wise Sum
[ 3 12 21]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [30]:
#please enter your code belowthis line.
import numpy as np
a = np.arange(0,16).reshape(4,4)
print(" Matrix")
print(a)
print("Minimum Value in Matrix")
print(np.min(a))
print("Maximum Value in Matrix")
print(np.max(a))
print("Mean of Matrix")
print(np.mean(a))

 Matrix
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Minimum Value in Matrix
0
Maximum Value in Matrix
15
Mean of Matrix
7.5


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [31]:
#please enter your code below this line.
import numpy as np
a = np.arange(0,100).reshape(10,10)
print("matrix")
print(a)
print("\n seventh Row")
print(a[7])
print(" \nRows from 4-8")
print(a[4:9,:])
print("\n 5 th column")
print(a[:,5])
print("\n columns from 2 - 5")
print(a[:,2:5])

matrix
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

 seventh Row
[70 71 72 73 74 75 76 77 78 79]
 
Rows from 4-8
[[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]]

 5 th column
[ 5 15 25 35 45 55 65 75 85 95]

 columns from 2 - 5
[[ 2  3  4]
 [12 13 14]
 [22 23 24]
 [32 33 34]
 [42 43 44]
 [52 53 54]
 [62 63 64]
 [72 73 74]
 [82 83 84]
 [92 93 94]]
