<a href="https://colab.research.google.com/github/Alen-8080/Learn.py/blob/main/TASK_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create two arrays, one containing elements [1,2], [3,4] and another containing elements [8,18] Now find the solution for this linear equation.

In [20]:
#please type your answer below this line.
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([8,18])
print(" Array A")
print(a)
print(" Array B ")
print(b)
print(" Solution for linear equation")
print(np.linalg.solve(a,b))

 Array A
[[1 2]
 [3 4]]
 Array B 
[ 8 18]
 Solution for linear equation
[2. 3.]


2. Create an array containing elements [2, 3, 4]. Now find the sin,cos,tan values of this array elements.

In [19]:
#please type your answer below this line.
import numpy as np
a = np.array([2,3,4])
print(" Array")
print(a)
print(" Sine of array")
print(np.sin(a))
print(" cosine of array")
print(np.cos(a))
print(" tan of array")
print(np.tan(a))

 Array
[2 3 4]
 Sine of array
[ 0.90929743  0.14112001 -0.7568025 ]
 cosine of array
[-0.41614684 -0.9899925  -0.65364362]
 tan of array
[-2.18503986 -0.14254654  1.15782128]


3. Given b=[5,6], then find,

  a) 2sinb
  b) 2cos3b
  c) 4tan2b

In [18]:
#please type your answer below this line.
import numpy as np
b = np.array([5,6])
print("Matrix b")
print(b)
print(" 2sinb")
print(2*np.sin(b))
print(" 2cos3b")
print(2*np.cos(3*b))
print(" 4tan2b")
print(4*np.tan(2*b))

Matrix b
[5 6]
 2sinb
[-1.91784855 -0.558831  ]
 2cos3b
[-1.51937583  1.32063342]
 4tan2b
[ 2.59344331 -2.54343971]
