<a href="https://colab.research.google.com/github/Alen-8080/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [3]:
#please provide your answer below this line.
import numpy as np
np.random.rand(3,3)

array([[0.40594217, 0.55079816, 0.7688454 ],
       [0.37239852, 0.97426336, 0.69628052],
       [0.48219739, 0.94194663, 0.51702799]])

2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [17]:
#please provide your answer below this line.
import numpy as np
a = np.arange(1,17).reshape(4,4)
b = np.arange(17,33).reshape(4,4)
print("1 st Array : ")
print(a)
print("2 nd Array : ")
print(b)
print("Vertical Stack : ")
print(np.vstack((a,b)))
print("Horizontal Stack : ")
print(np.hstack((a,b)))

1 st Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2 nd Array : 
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
Vertical Stack : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
Horizontal Stack : 
[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]
